#!/bin/bash

exec 2>&1

export REDIS_PORT="{{{ bind.cache.first.cfg.port }}}"
export REDIS_HOST="{{{ bind.cache.first.sys.ip }}}"

echo "Starting httpbin with redis $REDIS_HOST:$REDIS_PORT"

java -jar "{{{ pkg.path }}}/httpbin.jar"
